// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

#ifndef PROTOBUF_service_2eproto__INCLUDED
#define PROTOBUF_service_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace Lya {
namespace ProtocolBuffers {
class PBAvailabilityRequest;
class PBAvailabilityRequestDefaultTypeInternal;
extern PBAvailabilityRequestDefaultTypeInternal _PBAvailabilityRequest_default_instance_;
class PBAvailabilityResponse;
class PBAvailabilityResponseDefaultTypeInternal;
extern PBAvailabilityResponseDefaultTypeInternal _PBAvailabilityResponse_default_instance_;
class PBDiagnostic;
class PBDiagnosticDefaultTypeInternal;
extern PBDiagnosticDefaultTypeInternal _PBDiagnostic_default_instance_;
class PBFileToLocalizations;
class PBFileToLocalizationsDefaultTypeInternal;
extern PBFileToLocalizationsDefaultTypeInternal _PBFileToLocalizations_default_instance_;
class PBLocalization;
class PBLocalizationDefaultTypeInternal;
extern PBLocalizationDefaultTypeInternal _PBLocalization_default_instance_;
class PBLocation;
class PBLocationDefaultTypeInternal;
extern PBLocationDefaultTypeInternal _PBLocation_default_instance_;
class PBParam;
class PBParamDefaultTypeInternal;
extern PBParamDefaultTypeInternal _PBParam_default_instance_;
class PBSyncRequest;
class PBSyncRequestDefaultTypeInternal;
extern PBSyncRequestDefaultTypeInternal _PBSyncRequest_default_instance_;
class PBSyncResponse;
class PBSyncResponseDefaultTypeInternal;
extern PBSyncResponseDefaultTypeInternal _PBSyncResponse_default_instance_;
}  // namespace ProtocolBuffers
}  // namespace Lya

namespace Lya {
namespace ProtocolBuffers {

namespace protobuf_service_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_service_2eproto

// ===================================================================

class PBAvailabilityRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.ProtocolBuffers.PBAvailabilityRequest) */ {
 public:
  PBAvailabilityRequest();
  virtual ~PBAvailabilityRequest();

  PBAvailabilityRequest(const PBAvailabilityRequest& from);

  inline PBAvailabilityRequest& operator=(const PBAvailabilityRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBAvailabilityRequest& default_instance();

  static inline const PBAvailabilityRequest* internal_default_instance() {
    return reinterpret_cast<const PBAvailabilityRequest*>(
               &_PBAvailabilityRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PBAvailabilityRequest* other);

  // implements Message ----------------------------------------------

  inline PBAvailabilityRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  PBAvailabilityRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBAvailabilityRequest& from);
  void MergeFrom(const PBAvailabilityRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBAvailabilityRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Lya.ProtocolBuffers.PBAvailabilityRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBAvailabilityResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.ProtocolBuffers.PBAvailabilityResponse) */ {
 public:
  PBAvailabilityResponse();
  virtual ~PBAvailabilityResponse();

  PBAvailabilityResponse(const PBAvailabilityResponse& from);

  inline PBAvailabilityResponse& operator=(const PBAvailabilityResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBAvailabilityResponse& default_instance();

  static inline const PBAvailabilityResponse* internal_default_instance() {
    return reinterpret_cast<const PBAvailabilityResponse*>(
               &_PBAvailabilityResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(PBAvailabilityResponse* other);

  // implements Message ----------------------------------------------

  inline PBAvailabilityResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  PBAvailabilityResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBAvailabilityResponse& from);
  void MergeFrom(const PBAvailabilityResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBAvailabilityResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Lya.ProtocolBuffers.PBAvailabilityResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBSyncRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.ProtocolBuffers.PBSyncRequest) */ {
 public:
  PBSyncRequest();
  virtual ~PBSyncRequest();

  PBSyncRequest(const PBSyncRequest& from);

  inline PBSyncRequest& operator=(const PBSyncRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBSyncRequest& default_instance();

  static inline const PBSyncRequest* internal_default_instance() {
    return reinterpret_cast<const PBSyncRequest*>(
               &_PBSyncRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(PBSyncRequest* other);

  // implements Message ----------------------------------------------

  inline PBSyncRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  PBSyncRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBSyncRequest& from);
  void MergeFrom(const PBSyncRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBSyncRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string functions = 1;
  int functions_size() const;
  void clear_functions();
  static const int kFunctionsFieldNumber = 1;
  const ::std::string& functions(int index) const;
  ::std::string* mutable_functions(int index);
  void set_functions(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_functions(int index, ::std::string&& value);
  #endif
  void set_functions(int index, const char* value);
  void set_functions(int index, const char* value, size_t size);
  ::std::string* add_functions();
  void add_functions(const ::std::string& value);
  #if LANG_CXX11
  void add_functions(::std::string&& value);
  #endif
  void add_functions(const char* value);
  void add_functions(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& functions() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_functions();

  // repeated string files = 2;
  int files_size() const;
  void clear_files();
  static const int kFilesFieldNumber = 2;
  const ::std::string& files(int index) const;
  ::std::string* mutable_files(int index);
  void set_files(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_files(int index, ::std::string&& value);
  #endif
  void set_files(int index, const char* value);
  void set_files(int index, const char* value, size_t size);
  ::std::string* add_files();
  void add_files(const ::std::string& value);
  #if LANG_CXX11
  void add_files(::std::string&& value);
  #endif
  void add_files(const char* value);
  void add_files(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& files() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_files();

  // uint64 start_line = 3;
  void clear_start_line();
  static const int kStartLineFieldNumber = 3;
  ::google::protobuf::uint64 start_line() const;
  void set_start_line(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Lya.ProtocolBuffers.PBSyncRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> functions_;
  ::google::protobuf::RepeatedPtrField< ::std::string> files_;
  ::google::protobuf::uint64 start_line_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBSyncResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.ProtocolBuffers.PBSyncResponse) */ {
 public:
  PBSyncResponse();
  virtual ~PBSyncResponse();

  PBSyncResponse(const PBSyncResponse& from);

  inline PBSyncResponse& operator=(const PBSyncResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBSyncResponse& default_instance();

  static inline const PBSyncResponse* internal_default_instance() {
    return reinterpret_cast<const PBSyncResponse*>(
               &_PBSyncResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(PBSyncResponse* other);

  // implements Message ----------------------------------------------

  inline PBSyncResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  PBSyncResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBSyncResponse& from);
  void MergeFrom(const PBSyncResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBSyncResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Lya.ProtocolBuffers.PBFileToLocalizations file_to_localizations = 1;
  int file_to_localizations_size() const;
  void clear_file_to_localizations();
  static const int kFileToLocalizationsFieldNumber = 1;
  const ::Lya::ProtocolBuffers::PBFileToLocalizations& file_to_localizations(int index) const;
  ::Lya::ProtocolBuffers::PBFileToLocalizations* mutable_file_to_localizations(int index);
  ::Lya::ProtocolBuffers::PBFileToLocalizations* add_file_to_localizations();
  ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBFileToLocalizations >*
      mutable_file_to_localizations();
  const ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBFileToLocalizations >&
      file_to_localizations() const;

  // repeated .Lya.ProtocolBuffers.PBDiagnostic diagnostics = 2;
  int diagnostics_size() const;
  void clear_diagnostics();
  static const int kDiagnosticsFieldNumber = 2;
  const ::Lya::ProtocolBuffers::PBDiagnostic& diagnostics(int index) const;
  ::Lya::ProtocolBuffers::PBDiagnostic* mutable_diagnostics(int index);
  ::Lya::ProtocolBuffers::PBDiagnostic* add_diagnostics();
  ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBDiagnostic >*
      mutable_diagnostics();
  const ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBDiagnostic >&
      diagnostics() const;

  // @@protoc_insertion_point(class_scope:Lya.ProtocolBuffers.PBSyncResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBFileToLocalizations > file_to_localizations_;
  ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBDiagnostic > diagnostics_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBFileToLocalizations : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.ProtocolBuffers.PBFileToLocalizations) */ {
 public:
  PBFileToLocalizations();
  virtual ~PBFileToLocalizations();

  PBFileToLocalizations(const PBFileToLocalizations& from);

  inline PBFileToLocalizations& operator=(const PBFileToLocalizations& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBFileToLocalizations& default_instance();

  static inline const PBFileToLocalizations* internal_default_instance() {
    return reinterpret_cast<const PBFileToLocalizations*>(
               &_PBFileToLocalizations_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(PBFileToLocalizations* other);

  // implements Message ----------------------------------------------

  inline PBFileToLocalizations* New() const PROTOBUF_FINAL { return New(NULL); }

  PBFileToLocalizations* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBFileToLocalizations& from);
  void MergeFrom(const PBFileToLocalizations& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBFileToLocalizations* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Lya.ProtocolBuffers.PBLocalization localizations = 2;
  int localizations_size() const;
  void clear_localizations();
  static const int kLocalizationsFieldNumber = 2;
  const ::Lya::ProtocolBuffers::PBLocalization& localizations(int index) const;
  ::Lya::ProtocolBuffers::PBLocalization* mutable_localizations(int index);
  ::Lya::ProtocolBuffers::PBLocalization* add_localizations();
  ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBLocalization >*
      mutable_localizations();
  const ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBLocalization >&
      localizations() const;

  // string file = 1;
  void clear_file();
  static const int kFileFieldNumber = 1;
  const ::std::string& file() const;
  void set_file(const ::std::string& value);
  #if LANG_CXX11
  void set_file(::std::string&& value);
  #endif
  void set_file(const char* value);
  void set_file(const char* value, size_t size);
  ::std::string* mutable_file();
  ::std::string* release_file();
  void set_allocated_file(::std::string* file);

  // @@protoc_insertion_point(class_scope:Lya.ProtocolBuffers.PBFileToLocalizations)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBLocalization > localizations_;
  ::google::protobuf::internal::ArenaStringPtr file_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBLocalization : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.ProtocolBuffers.PBLocalization) */ {
 public:
  PBLocalization();
  virtual ~PBLocalization();

  PBLocalization(const PBLocalization& from);

  inline PBLocalization& operator=(const PBLocalization& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBLocalization& default_instance();

  static inline const PBLocalization* internal_default_instance() {
    return reinterpret_cast<const PBLocalization*>(
               &_PBLocalization_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(PBLocalization* other);

  // implements Message ----------------------------------------------

  inline PBLocalization* New() const PROTOBUF_FINAL { return New(NULL); }

  PBLocalization* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBLocalization& from);
  void MergeFrom(const PBLocalization& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBLocalization* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Lya.ProtocolBuffers.PBParam parameters = 3;
  int parameters_size() const;
  void clear_parameters();
  static const int kParametersFieldNumber = 3;
  const ::Lya::ProtocolBuffers::PBParam& parameters(int index) const;
  ::Lya::ProtocolBuffers::PBParam* mutable_parameters(int index);
  ::Lya::ProtocolBuffers::PBParam* add_parameters();
  ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBParam >*
      mutable_parameters();
  const ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBParam >&
      parameters() const;

  // string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // string text = 2;
  void clear_text();
  static const int kTextFieldNumber = 2;
  const ::std::string& text() const;
  void set_text(const ::std::string& value);
  #if LANG_CXX11
  void set_text(::std::string&& value);
  #endif
  void set_text(const char* value);
  void set_text(const char* value, size_t size);
  ::std::string* mutable_text();
  ::std::string* release_text();
  void set_allocated_text(::std::string* text);

  // .Lya.ProtocolBuffers.PBLocation location = 4;
  bool has_location() const;
  void clear_location();
  static const int kLocationFieldNumber = 4;
  const ::Lya::ProtocolBuffers::PBLocation& location() const;
  ::Lya::ProtocolBuffers::PBLocation* mutable_location();
  ::Lya::ProtocolBuffers::PBLocation* release_location();
  void set_allocated_location(::Lya::ProtocolBuffers::PBLocation* location);

  // @@protoc_insertion_point(class_scope:Lya.ProtocolBuffers.PBLocalization)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBParam > parameters_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr text_;
  ::Lya::ProtocolBuffers::PBLocation* location_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBParam : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.ProtocolBuffers.PBParam) */ {
 public:
  PBParam();
  virtual ~PBParam();

  PBParam(const PBParam& from);

  inline PBParam& operator=(const PBParam& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBParam& default_instance();

  static inline const PBParam* internal_default_instance() {
    return reinterpret_cast<const PBParam*>(
               &_PBParam_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(PBParam* other);

  // implements Message ----------------------------------------------

  inline PBParam* New() const PROTOBUF_FINAL { return New(NULL); }

  PBParam* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBParam& from);
  void MergeFrom(const PBParam& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBParam* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string type = 3;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  #if LANG_CXX11
  void set_type(::std::string&& value);
  #endif
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // bool is_list = 2;
  void clear_is_list();
  static const int kIsListFieldNumber = 2;
  bool is_list() const;
  void set_is_list(bool value);

  // @@protoc_insertion_point(class_scope:Lya.ProtocolBuffers.PBParam)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  bool is_list_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBDiagnostic : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.ProtocolBuffers.PBDiagnostic) */ {
 public:
  PBDiagnostic();
  virtual ~PBDiagnostic();

  PBDiagnostic(const PBDiagnostic& from);

  inline PBDiagnostic& operator=(const PBDiagnostic& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBDiagnostic& default_instance();

  static inline const PBDiagnostic* internal_default_instance() {
    return reinterpret_cast<const PBDiagnostic*>(
               &_PBDiagnostic_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(PBDiagnostic* other);

  // implements Message ----------------------------------------------

  inline PBDiagnostic* New() const PROTOBUF_FINAL { return New(NULL); }

  PBDiagnostic* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBDiagnostic& from);
  void MergeFrom(const PBDiagnostic& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBDiagnostic* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 1;
  void clear_message();
  static const int kMessageFieldNumber = 1;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // .Lya.ProtocolBuffers.PBLocation location = 2;
  bool has_location() const;
  void clear_location();
  static const int kLocationFieldNumber = 2;
  const ::Lya::ProtocolBuffers::PBLocation& location() const;
  ::Lya::ProtocolBuffers::PBLocation* mutable_location();
  ::Lya::ProtocolBuffers::PBLocation* release_location();
  void set_allocated_location(::Lya::ProtocolBuffers::PBLocation* location);

  // @@protoc_insertion_point(class_scope:Lya.ProtocolBuffers.PBDiagnostic)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::Lya::ProtocolBuffers::PBLocation* location_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBLocation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.ProtocolBuffers.PBLocation) */ {
 public:
  PBLocation();
  virtual ~PBLocation();

  PBLocation(const PBLocation& from);

  inline PBLocation& operator=(const PBLocation& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBLocation& default_instance();

  static inline const PBLocation* internal_default_instance() {
    return reinterpret_cast<const PBLocation*>(
               &_PBLocation_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(PBLocation* other);

  // implements Message ----------------------------------------------

  inline PBLocation* New() const PROTOBUF_FINAL { return New(NULL); }

  PBLocation* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBLocation& from);
  void MergeFrom(const PBLocation& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBLocation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 line = 1;
  void clear_line();
  static const int kLineFieldNumber = 1;
  ::google::protobuf::uint64 line() const;
  void set_line(::google::protobuf::uint64 value);

  // uint64 column = 2;
  void clear_column();
  static const int kColumnFieldNumber = 2;
  ::google::protobuf::uint64 column() const;
  void set_column(::google::protobuf::uint64 value);

  // uint64 length = 3;
  void clear_length();
  static const int kLengthFieldNumber = 3;
  ::google::protobuf::uint64 length() const;
  void set_length(::google::protobuf::uint64 value);

  // uint64 position = 4;
  void clear_position();
  static const int kPositionFieldNumber = 4;
  ::google::protobuf::uint64 position() const;
  void set_position(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Lya.ProtocolBuffers.PBLocation)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 line_;
  ::google::protobuf::uint64 column_;
  ::google::protobuf::uint64 length_;
  ::google::protobuf::uint64 position_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PBAvailabilityRequest

// -------------------------------------------------------------------

// PBAvailabilityResponse

// -------------------------------------------------------------------

// PBSyncRequest

// repeated string functions = 1;
inline int PBSyncRequest::functions_size() const {
  return functions_.size();
}
inline void PBSyncRequest::clear_functions() {
  functions_.Clear();
}
inline const ::std::string& PBSyncRequest::functions(int index) const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBSyncRequest.functions)
  return functions_.Get(index);
}
inline ::std::string* PBSyncRequest::mutable_functions(int index) {
  // @@protoc_insertion_point(field_mutable:Lya.ProtocolBuffers.PBSyncRequest.functions)
  return functions_.Mutable(index);
}
inline void PBSyncRequest::set_functions(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBSyncRequest.functions)
  functions_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void PBSyncRequest::set_functions(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBSyncRequest.functions)
  functions_.Mutable(index)->assign(std::move(value));
}
#endif
inline void PBSyncRequest::set_functions(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  functions_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Lya.ProtocolBuffers.PBSyncRequest.functions)
}
inline void PBSyncRequest::set_functions(int index, const char* value, size_t size) {
  functions_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Lya.ProtocolBuffers.PBSyncRequest.functions)
}
inline ::std::string* PBSyncRequest::add_functions() {
  // @@protoc_insertion_point(field_add_mutable:Lya.ProtocolBuffers.PBSyncRequest.functions)
  return functions_.Add();
}
inline void PBSyncRequest::add_functions(const ::std::string& value) {
  functions_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Lya.ProtocolBuffers.PBSyncRequest.functions)
}
#if LANG_CXX11
inline void PBSyncRequest::add_functions(::std::string&& value) {
  functions_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:Lya.ProtocolBuffers.PBSyncRequest.functions)
}
#endif
inline void PBSyncRequest::add_functions(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  functions_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Lya.ProtocolBuffers.PBSyncRequest.functions)
}
inline void PBSyncRequest::add_functions(const char* value, size_t size) {
  functions_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Lya.ProtocolBuffers.PBSyncRequest.functions)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
PBSyncRequest::functions() const {
  // @@protoc_insertion_point(field_list:Lya.ProtocolBuffers.PBSyncRequest.functions)
  return functions_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
PBSyncRequest::mutable_functions() {
  // @@protoc_insertion_point(field_mutable_list:Lya.ProtocolBuffers.PBSyncRequest.functions)
  return &functions_;
}

// repeated string files = 2;
inline int PBSyncRequest::files_size() const {
  return files_.size();
}
inline void PBSyncRequest::clear_files() {
  files_.Clear();
}
inline const ::std::string& PBSyncRequest::files(int index) const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBSyncRequest.files)
  return files_.Get(index);
}
inline ::std::string* PBSyncRequest::mutable_files(int index) {
  // @@protoc_insertion_point(field_mutable:Lya.ProtocolBuffers.PBSyncRequest.files)
  return files_.Mutable(index);
}
inline void PBSyncRequest::set_files(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBSyncRequest.files)
  files_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void PBSyncRequest::set_files(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBSyncRequest.files)
  files_.Mutable(index)->assign(std::move(value));
}
#endif
inline void PBSyncRequest::set_files(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  files_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Lya.ProtocolBuffers.PBSyncRequest.files)
}
inline void PBSyncRequest::set_files(int index, const char* value, size_t size) {
  files_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Lya.ProtocolBuffers.PBSyncRequest.files)
}
inline ::std::string* PBSyncRequest::add_files() {
  // @@protoc_insertion_point(field_add_mutable:Lya.ProtocolBuffers.PBSyncRequest.files)
  return files_.Add();
}
inline void PBSyncRequest::add_files(const ::std::string& value) {
  files_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Lya.ProtocolBuffers.PBSyncRequest.files)
}
#if LANG_CXX11
inline void PBSyncRequest::add_files(::std::string&& value) {
  files_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:Lya.ProtocolBuffers.PBSyncRequest.files)
}
#endif
inline void PBSyncRequest::add_files(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  files_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Lya.ProtocolBuffers.PBSyncRequest.files)
}
inline void PBSyncRequest::add_files(const char* value, size_t size) {
  files_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Lya.ProtocolBuffers.PBSyncRequest.files)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
PBSyncRequest::files() const {
  // @@protoc_insertion_point(field_list:Lya.ProtocolBuffers.PBSyncRequest.files)
  return files_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
PBSyncRequest::mutable_files() {
  // @@protoc_insertion_point(field_mutable_list:Lya.ProtocolBuffers.PBSyncRequest.files)
  return &files_;
}

// uint64 start_line = 3;
inline void PBSyncRequest::clear_start_line() {
  start_line_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PBSyncRequest::start_line() const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBSyncRequest.start_line)
  return start_line_;
}
inline void PBSyncRequest::set_start_line(::google::protobuf::uint64 value) {
  
  start_line_ = value;
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBSyncRequest.start_line)
}

// -------------------------------------------------------------------

// PBSyncResponse

// repeated .Lya.ProtocolBuffers.PBFileToLocalizations file_to_localizations = 1;
inline int PBSyncResponse::file_to_localizations_size() const {
  return file_to_localizations_.size();
}
inline void PBSyncResponse::clear_file_to_localizations() {
  file_to_localizations_.Clear();
}
inline const ::Lya::ProtocolBuffers::PBFileToLocalizations& PBSyncResponse::file_to_localizations(int index) const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBSyncResponse.file_to_localizations)
  return file_to_localizations_.Get(index);
}
inline ::Lya::ProtocolBuffers::PBFileToLocalizations* PBSyncResponse::mutable_file_to_localizations(int index) {
  // @@protoc_insertion_point(field_mutable:Lya.ProtocolBuffers.PBSyncResponse.file_to_localizations)
  return file_to_localizations_.Mutable(index);
}
inline ::Lya::ProtocolBuffers::PBFileToLocalizations* PBSyncResponse::add_file_to_localizations() {
  // @@protoc_insertion_point(field_add:Lya.ProtocolBuffers.PBSyncResponse.file_to_localizations)
  return file_to_localizations_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBFileToLocalizations >*
PBSyncResponse::mutable_file_to_localizations() {
  // @@protoc_insertion_point(field_mutable_list:Lya.ProtocolBuffers.PBSyncResponse.file_to_localizations)
  return &file_to_localizations_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBFileToLocalizations >&
PBSyncResponse::file_to_localizations() const {
  // @@protoc_insertion_point(field_list:Lya.ProtocolBuffers.PBSyncResponse.file_to_localizations)
  return file_to_localizations_;
}

// repeated .Lya.ProtocolBuffers.PBDiagnostic diagnostics = 2;
inline int PBSyncResponse::diagnostics_size() const {
  return diagnostics_.size();
}
inline void PBSyncResponse::clear_diagnostics() {
  diagnostics_.Clear();
}
inline const ::Lya::ProtocolBuffers::PBDiagnostic& PBSyncResponse::diagnostics(int index) const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBSyncResponse.diagnostics)
  return diagnostics_.Get(index);
}
inline ::Lya::ProtocolBuffers::PBDiagnostic* PBSyncResponse::mutable_diagnostics(int index) {
  // @@protoc_insertion_point(field_mutable:Lya.ProtocolBuffers.PBSyncResponse.diagnostics)
  return diagnostics_.Mutable(index);
}
inline ::Lya::ProtocolBuffers::PBDiagnostic* PBSyncResponse::add_diagnostics() {
  // @@protoc_insertion_point(field_add:Lya.ProtocolBuffers.PBSyncResponse.diagnostics)
  return diagnostics_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBDiagnostic >*
PBSyncResponse::mutable_diagnostics() {
  // @@protoc_insertion_point(field_mutable_list:Lya.ProtocolBuffers.PBSyncResponse.diagnostics)
  return &diagnostics_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBDiagnostic >&
PBSyncResponse::diagnostics() const {
  // @@protoc_insertion_point(field_list:Lya.ProtocolBuffers.PBSyncResponse.diagnostics)
  return diagnostics_;
}

// -------------------------------------------------------------------

// PBFileToLocalizations

// string file = 1;
inline void PBFileToLocalizations::clear_file() {
  file_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBFileToLocalizations::file() const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBFileToLocalizations.file)
  return file_.GetNoArena();
}
inline void PBFileToLocalizations::set_file(const ::std::string& value) {
  
  file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBFileToLocalizations.file)
}
#if LANG_CXX11
inline void PBFileToLocalizations::set_file(::std::string&& value) {
  
  file_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Lya.ProtocolBuffers.PBFileToLocalizations.file)
}
#endif
inline void PBFileToLocalizations::set_file(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Lya.ProtocolBuffers.PBFileToLocalizations.file)
}
inline void PBFileToLocalizations::set_file(const char* value, size_t size) {
  
  file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Lya.ProtocolBuffers.PBFileToLocalizations.file)
}
inline ::std::string* PBFileToLocalizations::mutable_file() {
  
  // @@protoc_insertion_point(field_mutable:Lya.ProtocolBuffers.PBFileToLocalizations.file)
  return file_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBFileToLocalizations::release_file() {
  // @@protoc_insertion_point(field_release:Lya.ProtocolBuffers.PBFileToLocalizations.file)
  
  return file_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBFileToLocalizations::set_allocated_file(::std::string* file) {
  if (file != NULL) {
    
  } else {
    
  }
  file_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), file);
  // @@protoc_insertion_point(field_set_allocated:Lya.ProtocolBuffers.PBFileToLocalizations.file)
}

// repeated .Lya.ProtocolBuffers.PBLocalization localizations = 2;
inline int PBFileToLocalizations::localizations_size() const {
  return localizations_.size();
}
inline void PBFileToLocalizations::clear_localizations() {
  localizations_.Clear();
}
inline const ::Lya::ProtocolBuffers::PBLocalization& PBFileToLocalizations::localizations(int index) const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBFileToLocalizations.localizations)
  return localizations_.Get(index);
}
inline ::Lya::ProtocolBuffers::PBLocalization* PBFileToLocalizations::mutable_localizations(int index) {
  // @@protoc_insertion_point(field_mutable:Lya.ProtocolBuffers.PBFileToLocalizations.localizations)
  return localizations_.Mutable(index);
}
inline ::Lya::ProtocolBuffers::PBLocalization* PBFileToLocalizations::add_localizations() {
  // @@protoc_insertion_point(field_add:Lya.ProtocolBuffers.PBFileToLocalizations.localizations)
  return localizations_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBLocalization >*
PBFileToLocalizations::mutable_localizations() {
  // @@protoc_insertion_point(field_mutable_list:Lya.ProtocolBuffers.PBFileToLocalizations.localizations)
  return &localizations_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBLocalization >&
PBFileToLocalizations::localizations() const {
  // @@protoc_insertion_point(field_list:Lya.ProtocolBuffers.PBFileToLocalizations.localizations)
  return localizations_;
}

// -------------------------------------------------------------------

// PBLocalization

// string id = 1;
inline void PBLocalization::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBLocalization::id() const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBLocalization.id)
  return id_.GetNoArena();
}
inline void PBLocalization::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBLocalization.id)
}
#if LANG_CXX11
inline void PBLocalization::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Lya.ProtocolBuffers.PBLocalization.id)
}
#endif
inline void PBLocalization::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Lya.ProtocolBuffers.PBLocalization.id)
}
inline void PBLocalization::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Lya.ProtocolBuffers.PBLocalization.id)
}
inline ::std::string* PBLocalization::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:Lya.ProtocolBuffers.PBLocalization.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBLocalization::release_id() {
  // @@protoc_insertion_point(field_release:Lya.ProtocolBuffers.PBLocalization.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBLocalization::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:Lya.ProtocolBuffers.PBLocalization.id)
}

// string text = 2;
inline void PBLocalization::clear_text() {
  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBLocalization::text() const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBLocalization.text)
  return text_.GetNoArena();
}
inline void PBLocalization::set_text(const ::std::string& value) {
  
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBLocalization.text)
}
#if LANG_CXX11
inline void PBLocalization::set_text(::std::string&& value) {
  
  text_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Lya.ProtocolBuffers.PBLocalization.text)
}
#endif
inline void PBLocalization::set_text(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Lya.ProtocolBuffers.PBLocalization.text)
}
inline void PBLocalization::set_text(const char* value, size_t size) {
  
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Lya.ProtocolBuffers.PBLocalization.text)
}
inline ::std::string* PBLocalization::mutable_text() {
  
  // @@protoc_insertion_point(field_mutable:Lya.ProtocolBuffers.PBLocalization.text)
  return text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBLocalization::release_text() {
  // @@protoc_insertion_point(field_release:Lya.ProtocolBuffers.PBLocalization.text)
  
  return text_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBLocalization::set_allocated_text(::std::string* text) {
  if (text != NULL) {
    
  } else {
    
  }
  text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:Lya.ProtocolBuffers.PBLocalization.text)
}

// repeated .Lya.ProtocolBuffers.PBParam parameters = 3;
inline int PBLocalization::parameters_size() const {
  return parameters_.size();
}
inline void PBLocalization::clear_parameters() {
  parameters_.Clear();
}
inline const ::Lya::ProtocolBuffers::PBParam& PBLocalization::parameters(int index) const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBLocalization.parameters)
  return parameters_.Get(index);
}
inline ::Lya::ProtocolBuffers::PBParam* PBLocalization::mutable_parameters(int index) {
  // @@protoc_insertion_point(field_mutable:Lya.ProtocolBuffers.PBLocalization.parameters)
  return parameters_.Mutable(index);
}
inline ::Lya::ProtocolBuffers::PBParam* PBLocalization::add_parameters() {
  // @@protoc_insertion_point(field_add:Lya.ProtocolBuffers.PBLocalization.parameters)
  return parameters_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBParam >*
PBLocalization::mutable_parameters() {
  // @@protoc_insertion_point(field_mutable_list:Lya.ProtocolBuffers.PBLocalization.parameters)
  return &parameters_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Lya::ProtocolBuffers::PBParam >&
PBLocalization::parameters() const {
  // @@protoc_insertion_point(field_list:Lya.ProtocolBuffers.PBLocalization.parameters)
  return parameters_;
}

// .Lya.ProtocolBuffers.PBLocation location = 4;
inline bool PBLocalization::has_location() const {
  return this != internal_default_instance() && location_ != NULL;
}
inline void PBLocalization::clear_location() {
  if (GetArenaNoVirtual() == NULL && location_ != NULL) delete location_;
  location_ = NULL;
}
inline const ::Lya::ProtocolBuffers::PBLocation& PBLocalization::location() const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBLocalization.location)
  return location_ != NULL ? *location_
                         : *::Lya::ProtocolBuffers::PBLocation::internal_default_instance();
}
inline ::Lya::ProtocolBuffers::PBLocation* PBLocalization::mutable_location() {
  
  if (location_ == NULL) {
    location_ = new ::Lya::ProtocolBuffers::PBLocation;
  }
  // @@protoc_insertion_point(field_mutable:Lya.ProtocolBuffers.PBLocalization.location)
  return location_;
}
inline ::Lya::ProtocolBuffers::PBLocation* PBLocalization::release_location() {
  // @@protoc_insertion_point(field_release:Lya.ProtocolBuffers.PBLocalization.location)
  
  ::Lya::ProtocolBuffers::PBLocation* temp = location_;
  location_ = NULL;
  return temp;
}
inline void PBLocalization::set_allocated_location(::Lya::ProtocolBuffers::PBLocation* location) {
  delete location_;
  location_ = location;
  if (location) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Lya.ProtocolBuffers.PBLocalization.location)
}

// -------------------------------------------------------------------

// PBParam

// string name = 1;
inline void PBParam::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBParam::name() const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBParam.name)
  return name_.GetNoArena();
}
inline void PBParam::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBParam.name)
}
#if LANG_CXX11
inline void PBParam::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Lya.ProtocolBuffers.PBParam.name)
}
#endif
inline void PBParam::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Lya.ProtocolBuffers.PBParam.name)
}
inline void PBParam::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Lya.ProtocolBuffers.PBParam.name)
}
inline ::std::string* PBParam::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:Lya.ProtocolBuffers.PBParam.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBParam::release_name() {
  // @@protoc_insertion_point(field_release:Lya.ProtocolBuffers.PBParam.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBParam::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Lya.ProtocolBuffers.PBParam.name)
}

// bool is_list = 2;
inline void PBParam::clear_is_list() {
  is_list_ = false;
}
inline bool PBParam::is_list() const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBParam.is_list)
  return is_list_;
}
inline void PBParam::set_is_list(bool value) {
  
  is_list_ = value;
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBParam.is_list)
}

// string type = 3;
inline void PBParam::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBParam::type() const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBParam.type)
  return type_.GetNoArena();
}
inline void PBParam::set_type(const ::std::string& value) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBParam.type)
}
#if LANG_CXX11
inline void PBParam::set_type(::std::string&& value) {
  
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Lya.ProtocolBuffers.PBParam.type)
}
#endif
inline void PBParam::set_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Lya.ProtocolBuffers.PBParam.type)
}
inline void PBParam::set_type(const char* value, size_t size) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Lya.ProtocolBuffers.PBParam.type)
}
inline ::std::string* PBParam::mutable_type() {
  
  // @@protoc_insertion_point(field_mutable:Lya.ProtocolBuffers.PBParam.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBParam::release_type() {
  // @@protoc_insertion_point(field_release:Lya.ProtocolBuffers.PBParam.type)
  
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBParam::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    
  } else {
    
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:Lya.ProtocolBuffers.PBParam.type)
}

// -------------------------------------------------------------------

// PBDiagnostic

// string message = 1;
inline void PBDiagnostic::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBDiagnostic::message() const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBDiagnostic.message)
  return message_.GetNoArena();
}
inline void PBDiagnostic::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBDiagnostic.message)
}
#if LANG_CXX11
inline void PBDiagnostic::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Lya.ProtocolBuffers.PBDiagnostic.message)
}
#endif
inline void PBDiagnostic::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Lya.ProtocolBuffers.PBDiagnostic.message)
}
inline void PBDiagnostic::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Lya.ProtocolBuffers.PBDiagnostic.message)
}
inline ::std::string* PBDiagnostic::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:Lya.ProtocolBuffers.PBDiagnostic.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBDiagnostic::release_message() {
  // @@protoc_insertion_point(field_release:Lya.ProtocolBuffers.PBDiagnostic.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBDiagnostic::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:Lya.ProtocolBuffers.PBDiagnostic.message)
}

// .Lya.ProtocolBuffers.PBLocation location = 2;
inline bool PBDiagnostic::has_location() const {
  return this != internal_default_instance() && location_ != NULL;
}
inline void PBDiagnostic::clear_location() {
  if (GetArenaNoVirtual() == NULL && location_ != NULL) delete location_;
  location_ = NULL;
}
inline const ::Lya::ProtocolBuffers::PBLocation& PBDiagnostic::location() const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBDiagnostic.location)
  return location_ != NULL ? *location_
                         : *::Lya::ProtocolBuffers::PBLocation::internal_default_instance();
}
inline ::Lya::ProtocolBuffers::PBLocation* PBDiagnostic::mutable_location() {
  
  if (location_ == NULL) {
    location_ = new ::Lya::ProtocolBuffers::PBLocation;
  }
  // @@protoc_insertion_point(field_mutable:Lya.ProtocolBuffers.PBDiagnostic.location)
  return location_;
}
inline ::Lya::ProtocolBuffers::PBLocation* PBDiagnostic::release_location() {
  // @@protoc_insertion_point(field_release:Lya.ProtocolBuffers.PBDiagnostic.location)
  
  ::Lya::ProtocolBuffers::PBLocation* temp = location_;
  location_ = NULL;
  return temp;
}
inline void PBDiagnostic::set_allocated_location(::Lya::ProtocolBuffers::PBLocation* location) {
  delete location_;
  location_ = location;
  if (location) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Lya.ProtocolBuffers.PBDiagnostic.location)
}

// -------------------------------------------------------------------

// PBLocation

// uint64 line = 1;
inline void PBLocation::clear_line() {
  line_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PBLocation::line() const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBLocation.line)
  return line_;
}
inline void PBLocation::set_line(::google::protobuf::uint64 value) {
  
  line_ = value;
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBLocation.line)
}

// uint64 column = 2;
inline void PBLocation::clear_column() {
  column_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PBLocation::column() const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBLocation.column)
  return column_;
}
inline void PBLocation::set_column(::google::protobuf::uint64 value) {
  
  column_ = value;
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBLocation.column)
}

// uint64 length = 3;
inline void PBLocation::clear_length() {
  length_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PBLocation::length() const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBLocation.length)
  return length_;
}
inline void PBLocation::set_length(::google::protobuf::uint64 value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBLocation.length)
}

// uint64 position = 4;
inline void PBLocation::clear_position() {
  position_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PBLocation::position() const {
  // @@protoc_insertion_point(field_get:Lya.ProtocolBuffers.PBLocation.position)
  return position_;
}
inline void PBLocation::set_position(::google::protobuf::uint64 value) {
  
  position_ = value;
  // @@protoc_insertion_point(field_set:Lya.ProtocolBuffers.PBLocation.position)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace ProtocolBuffers
}  // namespace Lya

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_service_2eproto__INCLUDED
