
sudo: required
dist: trusty
language: cpp

compiler:
  - gcc

script:
  - mkdir debug && cd debug
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - make run-tests
  - cd ../src/Extensions/javascript
  - npm install
  - tsc
  - ../../../bin/lya extension-run-tests

git:

  # Handle git submodules by ourselves.
  submodules: false

before_install:

  # Use sed to replace the SSH URL with the public URL, then initialize submodules.
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

  # libmicrohttpd
  - curl -O http://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.52.tar.gz
  - tar -xvf libmicrohttpd-0.9.52.tar.gz
  - cd libmicrohttpd-0.9.52
  - ./configure && make
  - sudo make install && sudo ldconfig
  - cd .. && sudo rm -rf libmicrohttpd-0.9.52

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
            - libboost-all-dev
            - libargtable2-dev
      env: COMPILER=clang++-3.7
