// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

#ifndef PROTOBUF_service_2eproto__INCLUDED
#define PROTOBUF_service_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace Lya {
namespace protos {
class PBAvailabilityRequest;
class PBAvailabilityRequestDefaultTypeInternal;
extern PBAvailabilityRequestDefaultTypeInternal _PBAvailabilityRequest_default_instance_;
class PBAvailabilityResponse;
class PBAvailabilityResponseDefaultTypeInternal;
extern PBAvailabilityResponseDefaultTypeInternal _PBAvailabilityResponse_default_instance_;
class PBCompileRequest;
class PBCompileRequestDefaultTypeInternal;
extern PBCompileRequestDefaultTypeInternal _PBCompileRequest_default_instance_;
class PBCompileResponse;
class PBCompileResponseDefaultTypeInternal;
extern PBCompileResponseDefaultTypeInternal _PBCompileResponse_default_instance_;
class PBDiagnostic;
class PBDiagnosticDefaultTypeInternal;
extern PBDiagnosticDefaultTypeInternal _PBDiagnostic_default_instance_;
class PBExtractRequest;
class PBExtractRequestDefaultTypeInternal;
extern PBExtractRequestDefaultTypeInternal _PBExtractRequest_default_instance_;
class PBExtractResponse;
class PBExtractResponseDefaultTypeInternal;
extern PBExtractResponseDefaultTypeInternal _PBExtractResponse_default_instance_;
class PBFileToLocalizations;
class PBFileToLocalizationsDefaultTypeInternal;
extern PBFileToLocalizationsDefaultTypeInternal _PBFileToLocalizations_default_instance_;
class PBLocalization;
class PBLocalizationDefaultTypeInternal;
extern PBLocalizationDefaultTypeInternal _PBLocalization_default_instance_;
class PBLocation;
class PBLocationDefaultTypeInternal;
extern PBLocationDefaultTypeInternal _PBLocation_default_instance_;
class PBParam;
class PBParamDefaultTypeInternal;
extern PBParamDefaultTypeInternal _PBParam_default_instance_;
}  // namespace protos
}  // namespace Lya

namespace Lya {
namespace protos {

namespace protobuf_service_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_service_2eproto

// ===================================================================

class PBAvailabilityRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.protos.PBAvailabilityRequest) */ {
 public:
  PBAvailabilityRequest();
  virtual ~PBAvailabilityRequest();

  PBAvailabilityRequest(const PBAvailabilityRequest& from);

  inline PBAvailabilityRequest& operator=(const PBAvailabilityRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBAvailabilityRequest& default_instance();

  static inline const PBAvailabilityRequest* internal_default_instance() {
    return reinterpret_cast<const PBAvailabilityRequest*>(
               &_PBAvailabilityRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PBAvailabilityRequest* other);

  // implements Message ----------------------------------------------

  inline PBAvailabilityRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  PBAvailabilityRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBAvailabilityRequest& from);
  void MergeFrom(const PBAvailabilityRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBAvailabilityRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Lya.protos.PBAvailabilityRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBAvailabilityResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.protos.PBAvailabilityResponse) */ {
 public:
  PBAvailabilityResponse();
  virtual ~PBAvailabilityResponse();

  PBAvailabilityResponse(const PBAvailabilityResponse& from);

  inline PBAvailabilityResponse& operator=(const PBAvailabilityResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBAvailabilityResponse& default_instance();

  static inline const PBAvailabilityResponse* internal_default_instance() {
    return reinterpret_cast<const PBAvailabilityResponse*>(
               &_PBAvailabilityResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(PBAvailabilityResponse* other);

  // implements Message ----------------------------------------------

  inline PBAvailabilityResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  PBAvailabilityResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBAvailabilityResponse& from);
  void MergeFrom(const PBAvailabilityResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBAvailabilityResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Lya.protos.PBAvailabilityResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBExtractRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.protos.PBExtractRequest) */ {
 public:
  PBExtractRequest();
  virtual ~PBExtractRequest();

  PBExtractRequest(const PBExtractRequest& from);

  inline PBExtractRequest& operator=(const PBExtractRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBExtractRequest& default_instance();

  static inline const PBExtractRequest* internal_default_instance() {
    return reinterpret_cast<const PBExtractRequest*>(
               &_PBExtractRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(PBExtractRequest* other);

  // implements Message ----------------------------------------------

  inline PBExtractRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  PBExtractRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBExtractRequest& from);
  void MergeFrom(const PBExtractRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBExtractRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string functions = 1;
  int functions_size() const;
  void clear_functions();
  static const int kFunctionsFieldNumber = 1;
  const ::std::string& functions(int index) const;
  ::std::string* mutable_functions(int index);
  void set_functions(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_functions(int index, ::std::string&& value);
  #endif
  void set_functions(int index, const char* value);
  void set_functions(int index, const char* value, size_t size);
  ::std::string* add_functions();
  void add_functions(const ::std::string& value);
  #if LANG_CXX11
  void add_functions(::std::string&& value);
  #endif
  void add_functions(const char* value);
  void add_functions(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& functions() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_functions();

  // repeated string files = 2;
  int files_size() const;
  void clear_files();
  static const int kFilesFieldNumber = 2;
  const ::std::string& files(int index) const;
  ::std::string* mutable_files(int index);
  void set_files(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_files(int index, ::std::string&& value);
  #endif
  void set_files(int index, const char* value);
  void set_files(int index, const char* value, size_t size);
  ::std::string* add_files();
  void add_files(const ::std::string& value);
  #if LANG_CXX11
  void add_files(::std::string&& value);
  #endif
  void add_files(const char* value);
  void add_files(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& files() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_files();

  // uint64 start_line = 3;
  void clear_start_line();
  static const int kStartLineFieldNumber = 3;
  ::google::protobuf::uint64 start_line() const;
  void set_start_line(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Lya.protos.PBExtractRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> functions_;
  ::google::protobuf::RepeatedPtrField< ::std::string> files_;
  ::google::protobuf::uint64 start_line_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBCompileRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.protos.PBCompileRequest) */ {
 public:
  PBCompileRequest();
  virtual ~PBCompileRequest();

  PBCompileRequest(const PBCompileRequest& from);

  inline PBCompileRequest& operator=(const PBCompileRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBCompileRequest& default_instance();

  static inline const PBCompileRequest* internal_default_instance() {
    return reinterpret_cast<const PBCompileRequest*>(
               &_PBCompileRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(PBCompileRequest* other);

  // implements Message ----------------------------------------------

  inline PBCompileRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  PBCompileRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBCompileRequest& from);
  void MergeFrom(const PBCompileRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBCompileRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string messages = 1;
  int messages_size() const;
  void clear_messages();
  static const int kMessagesFieldNumber = 1;
  const ::std::string& messages(int index) const;
  ::std::string* mutable_messages(int index);
  void set_messages(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_messages(int index, ::std::string&& value);
  #endif
  void set_messages(int index, const char* value);
  void set_messages(int index, const char* value, size_t size);
  ::std::string* add_messages();
  void add_messages(const ::std::string& value);
  #if LANG_CXX11
  void add_messages(::std::string&& value);
  #endif
  void add_messages(const char* value);
  void add_messages(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& messages() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_messages();

  // @@protoc_insertion_point(class_scope:Lya.protos.PBCompileRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> messages_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBCompileResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.protos.PBCompileResponse) */ {
 public:
  PBCompileResponse();
  virtual ~PBCompileResponse();

  PBCompileResponse(const PBCompileResponse& from);

  inline PBCompileResponse& operator=(const PBCompileResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBCompileResponse& default_instance();

  static inline const PBCompileResponse* internal_default_instance() {
    return reinterpret_cast<const PBCompileResponse*>(
               &_PBCompileResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(PBCompileResponse* other);

  // implements Message ----------------------------------------------

  inline PBCompileResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  PBCompileResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBCompileResponse& from);
  void MergeFrom(const PBCompileResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBCompileResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Lya.protos.PBCompileResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBExtractResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.protos.PBExtractResponse) */ {
 public:
  PBExtractResponse();
  virtual ~PBExtractResponse();

  PBExtractResponse(const PBExtractResponse& from);

  inline PBExtractResponse& operator=(const PBExtractResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBExtractResponse& default_instance();

  static inline const PBExtractResponse* internal_default_instance() {
    return reinterpret_cast<const PBExtractResponse*>(
               &_PBExtractResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(PBExtractResponse* other);

  // implements Message ----------------------------------------------

  inline PBExtractResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  PBExtractResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBExtractResponse& from);
  void MergeFrom(const PBExtractResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBExtractResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Lya.protos.PBFileToLocalizations file_to_localizations = 1;
  int file_to_localizations_size() const;
  void clear_file_to_localizations();
  static const int kFileToLocalizationsFieldNumber = 1;
  const ::Lya::protos::PBFileToLocalizations& file_to_localizations(int index) const;
  ::Lya::protos::PBFileToLocalizations* mutable_file_to_localizations(int index);
  ::Lya::protos::PBFileToLocalizations* add_file_to_localizations();
  ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBFileToLocalizations >*
      mutable_file_to_localizations();
  const ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBFileToLocalizations >&
      file_to_localizations() const;

  // repeated .Lya.protos.PBDiagnostic diagnostics = 2;
  int diagnostics_size() const;
  void clear_diagnostics();
  static const int kDiagnosticsFieldNumber = 2;
  const ::Lya::protos::PBDiagnostic& diagnostics(int index) const;
  ::Lya::protos::PBDiagnostic* mutable_diagnostics(int index);
  ::Lya::protos::PBDiagnostic* add_diagnostics();
  ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBDiagnostic >*
      mutable_diagnostics();
  const ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBDiagnostic >&
      diagnostics() const;

  // @@protoc_insertion_point(class_scope:Lya.protos.PBExtractResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBFileToLocalizations > file_to_localizations_;
  ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBDiagnostic > diagnostics_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBFileToLocalizations : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.protos.PBFileToLocalizations) */ {
 public:
  PBFileToLocalizations();
  virtual ~PBFileToLocalizations();

  PBFileToLocalizations(const PBFileToLocalizations& from);

  inline PBFileToLocalizations& operator=(const PBFileToLocalizations& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBFileToLocalizations& default_instance();

  static inline const PBFileToLocalizations* internal_default_instance() {
    return reinterpret_cast<const PBFileToLocalizations*>(
               &_PBFileToLocalizations_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(PBFileToLocalizations* other);

  // implements Message ----------------------------------------------

  inline PBFileToLocalizations* New() const PROTOBUF_FINAL { return New(NULL); }

  PBFileToLocalizations* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBFileToLocalizations& from);
  void MergeFrom(const PBFileToLocalizations& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBFileToLocalizations* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Lya.protos.PBLocalization localizations = 2;
  int localizations_size() const;
  void clear_localizations();
  static const int kLocalizationsFieldNumber = 2;
  const ::Lya::protos::PBLocalization& localizations(int index) const;
  ::Lya::protos::PBLocalization* mutable_localizations(int index);
  ::Lya::protos::PBLocalization* add_localizations();
  ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBLocalization >*
      mutable_localizations();
  const ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBLocalization >&
      localizations() const;

  // string file = 1;
  void clear_file();
  static const int kFileFieldNumber = 1;
  const ::std::string& file() const;
  void set_file(const ::std::string& value);
  #if LANG_CXX11
  void set_file(::std::string&& value);
  #endif
  void set_file(const char* value);
  void set_file(const char* value, size_t size);
  ::std::string* mutable_file();
  ::std::string* release_file();
  void set_allocated_file(::std::string* file);

  // @@protoc_insertion_point(class_scope:Lya.protos.PBFileToLocalizations)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBLocalization > localizations_;
  ::google::protobuf::internal::ArenaStringPtr file_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBLocalization : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.protos.PBLocalization) */ {
 public:
  PBLocalization();
  virtual ~PBLocalization();

  PBLocalization(const PBLocalization& from);

  inline PBLocalization& operator=(const PBLocalization& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBLocalization& default_instance();

  static inline const PBLocalization* internal_default_instance() {
    return reinterpret_cast<const PBLocalization*>(
               &_PBLocalization_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(PBLocalization* other);

  // implements Message ----------------------------------------------

  inline PBLocalization* New() const PROTOBUF_FINAL { return New(NULL); }

  PBLocalization* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBLocalization& from);
  void MergeFrom(const PBLocalization& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBLocalization* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Lya.protos.PBParam parameters = 3;
  int parameters_size() const;
  void clear_parameters();
  static const int kParametersFieldNumber = 3;
  const ::Lya::protos::PBParam& parameters(int index) const;
  ::Lya::protos::PBParam* mutable_parameters(int index);
  ::Lya::protos::PBParam* add_parameters();
  ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBParam >*
      mutable_parameters();
  const ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBParam >&
      parameters() const;

  // string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // string text = 2;
  void clear_text();
  static const int kTextFieldNumber = 2;
  const ::std::string& text() const;
  void set_text(const ::std::string& value);
  #if LANG_CXX11
  void set_text(::std::string&& value);
  #endif
  void set_text(const char* value);
  void set_text(const char* value, size_t size);
  ::std::string* mutable_text();
  ::std::string* release_text();
  void set_allocated_text(::std::string* text);

  // .Lya.protos.PBLocation location = 4;
  bool has_location() const;
  void clear_location();
  static const int kLocationFieldNumber = 4;
  const ::Lya::protos::PBLocation& location() const;
  ::Lya::protos::PBLocation* mutable_location();
  ::Lya::protos::PBLocation* release_location();
  void set_allocated_location(::Lya::protos::PBLocation* location);

  // @@protoc_insertion_point(class_scope:Lya.protos.PBLocalization)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBParam > parameters_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr text_;
  ::Lya::protos::PBLocation* location_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBParam : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.protos.PBParam) */ {
 public:
  PBParam();
  virtual ~PBParam();

  PBParam(const PBParam& from);

  inline PBParam& operator=(const PBParam& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBParam& default_instance();

  static inline const PBParam* internal_default_instance() {
    return reinterpret_cast<const PBParam*>(
               &_PBParam_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(PBParam* other);

  // implements Message ----------------------------------------------

  inline PBParam* New() const PROTOBUF_FINAL { return New(NULL); }

  PBParam* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBParam& from);
  void MergeFrom(const PBParam& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBParam* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string type = 3;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  #if LANG_CXX11
  void set_type(::std::string&& value);
  #endif
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // bool is_list = 2;
  void clear_is_list();
  static const int kIsListFieldNumber = 2;
  bool is_list() const;
  void set_is_list(bool value);

  // @@protoc_insertion_point(class_scope:Lya.protos.PBParam)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  bool is_list_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBDiagnostic : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.protos.PBDiagnostic) */ {
 public:
  PBDiagnostic();
  virtual ~PBDiagnostic();

  PBDiagnostic(const PBDiagnostic& from);

  inline PBDiagnostic& operator=(const PBDiagnostic& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBDiagnostic& default_instance();

  static inline const PBDiagnostic* internal_default_instance() {
    return reinterpret_cast<const PBDiagnostic*>(
               &_PBDiagnostic_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(PBDiagnostic* other);

  // implements Message ----------------------------------------------

  inline PBDiagnostic* New() const PROTOBUF_FINAL { return New(NULL); }

  PBDiagnostic* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBDiagnostic& from);
  void MergeFrom(const PBDiagnostic& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBDiagnostic* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 1;
  void clear_message();
  static const int kMessageFieldNumber = 1;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // .Lya.protos.PBLocation location = 2;
  bool has_location() const;
  void clear_location();
  static const int kLocationFieldNumber = 2;
  const ::Lya::protos::PBLocation& location() const;
  ::Lya::protos::PBLocation* mutable_location();
  ::Lya::protos::PBLocation* release_location();
  void set_allocated_location(::Lya::protos::PBLocation* location);

  // @@protoc_insertion_point(class_scope:Lya.protos.PBDiagnostic)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::Lya::protos::PBLocation* location_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBLocation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lya.protos.PBLocation) */ {
 public:
  PBLocation();
  virtual ~PBLocation();

  PBLocation(const PBLocation& from);

  inline PBLocation& operator=(const PBLocation& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBLocation& default_instance();

  static inline const PBLocation* internal_default_instance() {
    return reinterpret_cast<const PBLocation*>(
               &_PBLocation_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    10;

  void Swap(PBLocation* other);

  // implements Message ----------------------------------------------

  inline PBLocation* New() const PROTOBUF_FINAL { return New(NULL); }

  PBLocation* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PBLocation& from);
  void MergeFrom(const PBLocation& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PBLocation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 line = 1;
  void clear_line();
  static const int kLineFieldNumber = 1;
  ::google::protobuf::uint64 line() const;
  void set_line(::google::protobuf::uint64 value);

  // uint64 column = 2;
  void clear_column();
  static const int kColumnFieldNumber = 2;
  ::google::protobuf::uint64 column() const;
  void set_column(::google::protobuf::uint64 value);

  // uint64 length = 3;
  void clear_length();
  static const int kLengthFieldNumber = 3;
  ::google::protobuf::uint64 length() const;
  void set_length(::google::protobuf::uint64 value);

  // uint64 position = 4;
  void clear_position();
  static const int kPositionFieldNumber = 4;
  ::google::protobuf::uint64 position() const;
  void set_position(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Lya.protos.PBLocation)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 line_;
  ::google::protobuf::uint64 column_;
  ::google::protobuf::uint64 length_;
  ::google::protobuf::uint64 position_;
  mutable int _cached_size_;
  friend struct protobuf_service_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PBAvailabilityRequest

// -------------------------------------------------------------------

// PBAvailabilityResponse

// -------------------------------------------------------------------

// PBExtractRequest

// repeated string functions = 1;
inline int PBExtractRequest::functions_size() const {
  return functions_.size();
}
inline void PBExtractRequest::clear_functions() {
  functions_.Clear();
}
inline const ::std::string& PBExtractRequest::functions(int index) const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBExtractRequest.functions)
  return functions_.Get(index);
}
inline ::std::string* PBExtractRequest::mutable_functions(int index) {
  // @@protoc_insertion_point(field_mutable:Lya.protos.PBExtractRequest.functions)
  return functions_.Mutable(index);
}
inline void PBExtractRequest::set_functions(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Lya.protos.PBExtractRequest.functions)
  functions_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void PBExtractRequest::set_functions(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:Lya.protos.PBExtractRequest.functions)
  functions_.Mutable(index)->assign(std::move(value));
}
#endif
inline void PBExtractRequest::set_functions(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  functions_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Lya.protos.PBExtractRequest.functions)
}
inline void PBExtractRequest::set_functions(int index, const char* value, size_t size) {
  functions_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Lya.protos.PBExtractRequest.functions)
}
inline ::std::string* PBExtractRequest::add_functions() {
  // @@protoc_insertion_point(field_add_mutable:Lya.protos.PBExtractRequest.functions)
  return functions_.Add();
}
inline void PBExtractRequest::add_functions(const ::std::string& value) {
  functions_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Lya.protos.PBExtractRequest.functions)
}
#if LANG_CXX11
inline void PBExtractRequest::add_functions(::std::string&& value) {
  functions_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:Lya.protos.PBExtractRequest.functions)
}
#endif
inline void PBExtractRequest::add_functions(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  functions_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Lya.protos.PBExtractRequest.functions)
}
inline void PBExtractRequest::add_functions(const char* value, size_t size) {
  functions_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Lya.protos.PBExtractRequest.functions)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
PBExtractRequest::functions() const {
  // @@protoc_insertion_point(field_list:Lya.protos.PBExtractRequest.functions)
  return functions_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
PBExtractRequest::mutable_functions() {
  // @@protoc_insertion_point(field_mutable_list:Lya.protos.PBExtractRequest.functions)
  return &functions_;
}

// repeated string files = 2;
inline int PBExtractRequest::files_size() const {
  return files_.size();
}
inline void PBExtractRequest::clear_files() {
  files_.Clear();
}
inline const ::std::string& PBExtractRequest::files(int index) const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBExtractRequest.files)
  return files_.Get(index);
}
inline ::std::string* PBExtractRequest::mutable_files(int index) {
  // @@protoc_insertion_point(field_mutable:Lya.protos.PBExtractRequest.files)
  return files_.Mutable(index);
}
inline void PBExtractRequest::set_files(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Lya.protos.PBExtractRequest.files)
  files_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void PBExtractRequest::set_files(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:Lya.protos.PBExtractRequest.files)
  files_.Mutable(index)->assign(std::move(value));
}
#endif
inline void PBExtractRequest::set_files(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  files_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Lya.protos.PBExtractRequest.files)
}
inline void PBExtractRequest::set_files(int index, const char* value, size_t size) {
  files_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Lya.protos.PBExtractRequest.files)
}
inline ::std::string* PBExtractRequest::add_files() {
  // @@protoc_insertion_point(field_add_mutable:Lya.protos.PBExtractRequest.files)
  return files_.Add();
}
inline void PBExtractRequest::add_files(const ::std::string& value) {
  files_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Lya.protos.PBExtractRequest.files)
}
#if LANG_CXX11
inline void PBExtractRequest::add_files(::std::string&& value) {
  files_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:Lya.protos.PBExtractRequest.files)
}
#endif
inline void PBExtractRequest::add_files(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  files_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Lya.protos.PBExtractRequest.files)
}
inline void PBExtractRequest::add_files(const char* value, size_t size) {
  files_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Lya.protos.PBExtractRequest.files)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
PBExtractRequest::files() const {
  // @@protoc_insertion_point(field_list:Lya.protos.PBExtractRequest.files)
  return files_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
PBExtractRequest::mutable_files() {
  // @@protoc_insertion_point(field_mutable_list:Lya.protos.PBExtractRequest.files)
  return &files_;
}

// uint64 start_line = 3;
inline void PBExtractRequest::clear_start_line() {
  start_line_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PBExtractRequest::start_line() const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBExtractRequest.start_line)
  return start_line_;
}
inline void PBExtractRequest::set_start_line(::google::protobuf::uint64 value) {
  
  start_line_ = value;
  // @@protoc_insertion_point(field_set:Lya.protos.PBExtractRequest.start_line)
}

// -------------------------------------------------------------------

// PBCompileRequest

// repeated string messages = 1;
inline int PBCompileRequest::messages_size() const {
  return messages_.size();
}
inline void PBCompileRequest::clear_messages() {
  messages_.Clear();
}
inline const ::std::string& PBCompileRequest::messages(int index) const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBCompileRequest.messages)
  return messages_.Get(index);
}
inline ::std::string* PBCompileRequest::mutable_messages(int index) {
  // @@protoc_insertion_point(field_mutable:Lya.protos.PBCompileRequest.messages)
  return messages_.Mutable(index);
}
inline void PBCompileRequest::set_messages(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Lya.protos.PBCompileRequest.messages)
  messages_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void PBCompileRequest::set_messages(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:Lya.protos.PBCompileRequest.messages)
  messages_.Mutable(index)->assign(std::move(value));
}
#endif
inline void PBCompileRequest::set_messages(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  messages_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Lya.protos.PBCompileRequest.messages)
}
inline void PBCompileRequest::set_messages(int index, const char* value, size_t size) {
  messages_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Lya.protos.PBCompileRequest.messages)
}
inline ::std::string* PBCompileRequest::add_messages() {
  // @@protoc_insertion_point(field_add_mutable:Lya.protos.PBCompileRequest.messages)
  return messages_.Add();
}
inline void PBCompileRequest::add_messages(const ::std::string& value) {
  messages_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Lya.protos.PBCompileRequest.messages)
}
#if LANG_CXX11
inline void PBCompileRequest::add_messages(::std::string&& value) {
  messages_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:Lya.protos.PBCompileRequest.messages)
}
#endif
inline void PBCompileRequest::add_messages(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  messages_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Lya.protos.PBCompileRequest.messages)
}
inline void PBCompileRequest::add_messages(const char* value, size_t size) {
  messages_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Lya.protos.PBCompileRequest.messages)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
PBCompileRequest::messages() const {
  // @@protoc_insertion_point(field_list:Lya.protos.PBCompileRequest.messages)
  return messages_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
PBCompileRequest::mutable_messages() {
  // @@protoc_insertion_point(field_mutable_list:Lya.protos.PBCompileRequest.messages)
  return &messages_;
}

// -------------------------------------------------------------------

// PBCompileResponse

// -------------------------------------------------------------------

// PBExtractResponse

// repeated .Lya.protos.PBFileToLocalizations file_to_localizations = 1;
inline int PBExtractResponse::file_to_localizations_size() const {
  return file_to_localizations_.size();
}
inline void PBExtractResponse::clear_file_to_localizations() {
  file_to_localizations_.Clear();
}
inline const ::Lya::protos::PBFileToLocalizations& PBExtractResponse::file_to_localizations(int index) const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBExtractResponse.file_to_localizations)
  return file_to_localizations_.Get(index);
}
inline ::Lya::protos::PBFileToLocalizations* PBExtractResponse::mutable_file_to_localizations(int index) {
  // @@protoc_insertion_point(field_mutable:Lya.protos.PBExtractResponse.file_to_localizations)
  return file_to_localizations_.Mutable(index);
}
inline ::Lya::protos::PBFileToLocalizations* PBExtractResponse::add_file_to_localizations() {
  // @@protoc_insertion_point(field_add:Lya.protos.PBExtractResponse.file_to_localizations)
  return file_to_localizations_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBFileToLocalizations >*
PBExtractResponse::mutable_file_to_localizations() {
  // @@protoc_insertion_point(field_mutable_list:Lya.protos.PBExtractResponse.file_to_localizations)
  return &file_to_localizations_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBFileToLocalizations >&
PBExtractResponse::file_to_localizations() const {
  // @@protoc_insertion_point(field_list:Lya.protos.PBExtractResponse.file_to_localizations)
  return file_to_localizations_;
}

// repeated .Lya.protos.PBDiagnostic diagnostics = 2;
inline int PBExtractResponse::diagnostics_size() const {
  return diagnostics_.size();
}
inline void PBExtractResponse::clear_diagnostics() {
  diagnostics_.Clear();
}
inline const ::Lya::protos::PBDiagnostic& PBExtractResponse::diagnostics(int index) const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBExtractResponse.diagnostics)
  return diagnostics_.Get(index);
}
inline ::Lya::protos::PBDiagnostic* PBExtractResponse::mutable_diagnostics(int index) {
  // @@protoc_insertion_point(field_mutable:Lya.protos.PBExtractResponse.diagnostics)
  return diagnostics_.Mutable(index);
}
inline ::Lya::protos::PBDiagnostic* PBExtractResponse::add_diagnostics() {
  // @@protoc_insertion_point(field_add:Lya.protos.PBExtractResponse.diagnostics)
  return diagnostics_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBDiagnostic >*
PBExtractResponse::mutable_diagnostics() {
  // @@protoc_insertion_point(field_mutable_list:Lya.protos.PBExtractResponse.diagnostics)
  return &diagnostics_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBDiagnostic >&
PBExtractResponse::diagnostics() const {
  // @@protoc_insertion_point(field_list:Lya.protos.PBExtractResponse.diagnostics)
  return diagnostics_;
}

// -------------------------------------------------------------------

// PBFileToLocalizations

// string file = 1;
inline void PBFileToLocalizations::clear_file() {
  file_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBFileToLocalizations::file() const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBFileToLocalizations.file)
  return file_.GetNoArena();
}
inline void PBFileToLocalizations::set_file(const ::std::string& value) {
  
  file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Lya.protos.PBFileToLocalizations.file)
}
#if LANG_CXX11
inline void PBFileToLocalizations::set_file(::std::string&& value) {
  
  file_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Lya.protos.PBFileToLocalizations.file)
}
#endif
inline void PBFileToLocalizations::set_file(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Lya.protos.PBFileToLocalizations.file)
}
inline void PBFileToLocalizations::set_file(const char* value, size_t size) {
  
  file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Lya.protos.PBFileToLocalizations.file)
}
inline ::std::string* PBFileToLocalizations::mutable_file() {
  
  // @@protoc_insertion_point(field_mutable:Lya.protos.PBFileToLocalizations.file)
  return file_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBFileToLocalizations::release_file() {
  // @@protoc_insertion_point(field_release:Lya.protos.PBFileToLocalizations.file)
  
  return file_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBFileToLocalizations::set_allocated_file(::std::string* file) {
  if (file != NULL) {
    
  } else {
    
  }
  file_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), file);
  // @@protoc_insertion_point(field_set_allocated:Lya.protos.PBFileToLocalizations.file)
}

// repeated .Lya.protos.PBLocalization localizations = 2;
inline int PBFileToLocalizations::localizations_size() const {
  return localizations_.size();
}
inline void PBFileToLocalizations::clear_localizations() {
  localizations_.Clear();
}
inline const ::Lya::protos::PBLocalization& PBFileToLocalizations::localizations(int index) const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBFileToLocalizations.localizations)
  return localizations_.Get(index);
}
inline ::Lya::protos::PBLocalization* PBFileToLocalizations::mutable_localizations(int index) {
  // @@protoc_insertion_point(field_mutable:Lya.protos.PBFileToLocalizations.localizations)
  return localizations_.Mutable(index);
}
inline ::Lya::protos::PBLocalization* PBFileToLocalizations::add_localizations() {
  // @@protoc_insertion_point(field_add:Lya.protos.PBFileToLocalizations.localizations)
  return localizations_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBLocalization >*
PBFileToLocalizations::mutable_localizations() {
  // @@protoc_insertion_point(field_mutable_list:Lya.protos.PBFileToLocalizations.localizations)
  return &localizations_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBLocalization >&
PBFileToLocalizations::localizations() const {
  // @@protoc_insertion_point(field_list:Lya.protos.PBFileToLocalizations.localizations)
  return localizations_;
}

// -------------------------------------------------------------------

// PBLocalization

// string id = 1;
inline void PBLocalization::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBLocalization::id() const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBLocalization.id)
  return id_.GetNoArena();
}
inline void PBLocalization::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Lya.protos.PBLocalization.id)
}
#if LANG_CXX11
inline void PBLocalization::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Lya.protos.PBLocalization.id)
}
#endif
inline void PBLocalization::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Lya.protos.PBLocalization.id)
}
inline void PBLocalization::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Lya.protos.PBLocalization.id)
}
inline ::std::string* PBLocalization::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:Lya.protos.PBLocalization.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBLocalization::release_id() {
  // @@protoc_insertion_point(field_release:Lya.protos.PBLocalization.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBLocalization::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:Lya.protos.PBLocalization.id)
}

// string text = 2;
inline void PBLocalization::clear_text() {
  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBLocalization::text() const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBLocalization.text)
  return text_.GetNoArena();
}
inline void PBLocalization::set_text(const ::std::string& value) {
  
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Lya.protos.PBLocalization.text)
}
#if LANG_CXX11
inline void PBLocalization::set_text(::std::string&& value) {
  
  text_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Lya.protos.PBLocalization.text)
}
#endif
inline void PBLocalization::set_text(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Lya.protos.PBLocalization.text)
}
inline void PBLocalization::set_text(const char* value, size_t size) {
  
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Lya.protos.PBLocalization.text)
}
inline ::std::string* PBLocalization::mutable_text() {
  
  // @@protoc_insertion_point(field_mutable:Lya.protos.PBLocalization.text)
  return text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBLocalization::release_text() {
  // @@protoc_insertion_point(field_release:Lya.protos.PBLocalization.text)
  
  return text_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBLocalization::set_allocated_text(::std::string* text) {
  if (text != NULL) {
    
  } else {
    
  }
  text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:Lya.protos.PBLocalization.text)
}

// repeated .Lya.protos.PBParam parameters = 3;
inline int PBLocalization::parameters_size() const {
  return parameters_.size();
}
inline void PBLocalization::clear_parameters() {
  parameters_.Clear();
}
inline const ::Lya::protos::PBParam& PBLocalization::parameters(int index) const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBLocalization.parameters)
  return parameters_.Get(index);
}
inline ::Lya::protos::PBParam* PBLocalization::mutable_parameters(int index) {
  // @@protoc_insertion_point(field_mutable:Lya.protos.PBLocalization.parameters)
  return parameters_.Mutable(index);
}
inline ::Lya::protos::PBParam* PBLocalization::add_parameters() {
  // @@protoc_insertion_point(field_add:Lya.protos.PBLocalization.parameters)
  return parameters_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBParam >*
PBLocalization::mutable_parameters() {
  // @@protoc_insertion_point(field_mutable_list:Lya.protos.PBLocalization.parameters)
  return &parameters_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Lya::protos::PBParam >&
PBLocalization::parameters() const {
  // @@protoc_insertion_point(field_list:Lya.protos.PBLocalization.parameters)
  return parameters_;
}

// .Lya.protos.PBLocation location = 4;
inline bool PBLocalization::has_location() const {
  return this != internal_default_instance() && location_ != NULL;
}
inline void PBLocalization::clear_location() {
  if (GetArenaNoVirtual() == NULL && location_ != NULL) delete location_;
  location_ = NULL;
}
inline const ::Lya::protos::PBLocation& PBLocalization::location() const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBLocalization.location)
  return location_ != NULL ? *location_
                         : *::Lya::protos::PBLocation::internal_default_instance();
}
inline ::Lya::protos::PBLocation* PBLocalization::mutable_location() {
  
  if (location_ == NULL) {
    location_ = new ::Lya::protos::PBLocation;
  }
  // @@protoc_insertion_point(field_mutable:Lya.protos.PBLocalization.location)
  return location_;
}
inline ::Lya::protos::PBLocation* PBLocalization::release_location() {
  // @@protoc_insertion_point(field_release:Lya.protos.PBLocalization.location)
  
  ::Lya::protos::PBLocation* temp = location_;
  location_ = NULL;
  return temp;
}
inline void PBLocalization::set_allocated_location(::Lya::protos::PBLocation* location) {
  delete location_;
  location_ = location;
  if (location) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Lya.protos.PBLocalization.location)
}

// -------------------------------------------------------------------

// PBParam

// string name = 1;
inline void PBParam::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBParam::name() const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBParam.name)
  return name_.GetNoArena();
}
inline void PBParam::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Lya.protos.PBParam.name)
}
#if LANG_CXX11
inline void PBParam::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Lya.protos.PBParam.name)
}
#endif
inline void PBParam::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Lya.protos.PBParam.name)
}
inline void PBParam::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Lya.protos.PBParam.name)
}
inline ::std::string* PBParam::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:Lya.protos.PBParam.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBParam::release_name() {
  // @@protoc_insertion_point(field_release:Lya.protos.PBParam.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBParam::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Lya.protos.PBParam.name)
}

// bool is_list = 2;
inline void PBParam::clear_is_list() {
  is_list_ = false;
}
inline bool PBParam::is_list() const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBParam.is_list)
  return is_list_;
}
inline void PBParam::set_is_list(bool value) {
  
  is_list_ = value;
  // @@protoc_insertion_point(field_set:Lya.protos.PBParam.is_list)
}

// string type = 3;
inline void PBParam::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBParam::type() const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBParam.type)
  return type_.GetNoArena();
}
inline void PBParam::set_type(const ::std::string& value) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Lya.protos.PBParam.type)
}
#if LANG_CXX11
inline void PBParam::set_type(::std::string&& value) {
  
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Lya.protos.PBParam.type)
}
#endif
inline void PBParam::set_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Lya.protos.PBParam.type)
}
inline void PBParam::set_type(const char* value, size_t size) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Lya.protos.PBParam.type)
}
inline ::std::string* PBParam::mutable_type() {
  
  // @@protoc_insertion_point(field_mutable:Lya.protos.PBParam.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBParam::release_type() {
  // @@protoc_insertion_point(field_release:Lya.protos.PBParam.type)
  
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBParam::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    
  } else {
    
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:Lya.protos.PBParam.type)
}

// -------------------------------------------------------------------

// PBDiagnostic

// string message = 1;
inline void PBDiagnostic::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBDiagnostic::message() const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBDiagnostic.message)
  return message_.GetNoArena();
}
inline void PBDiagnostic::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Lya.protos.PBDiagnostic.message)
}
#if LANG_CXX11
inline void PBDiagnostic::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Lya.protos.PBDiagnostic.message)
}
#endif
inline void PBDiagnostic::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Lya.protos.PBDiagnostic.message)
}
inline void PBDiagnostic::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Lya.protos.PBDiagnostic.message)
}
inline ::std::string* PBDiagnostic::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:Lya.protos.PBDiagnostic.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBDiagnostic::release_message() {
  // @@protoc_insertion_point(field_release:Lya.protos.PBDiagnostic.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBDiagnostic::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:Lya.protos.PBDiagnostic.message)
}

// .Lya.protos.PBLocation location = 2;
inline bool PBDiagnostic::has_location() const {
  return this != internal_default_instance() && location_ != NULL;
}
inline void PBDiagnostic::clear_location() {
  if (GetArenaNoVirtual() == NULL && location_ != NULL) delete location_;
  location_ = NULL;
}
inline const ::Lya::protos::PBLocation& PBDiagnostic::location() const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBDiagnostic.location)
  return location_ != NULL ? *location_
                         : *::Lya::protos::PBLocation::internal_default_instance();
}
inline ::Lya::protos::PBLocation* PBDiagnostic::mutable_location() {
  
  if (location_ == NULL) {
    location_ = new ::Lya::protos::PBLocation;
  }
  // @@protoc_insertion_point(field_mutable:Lya.protos.PBDiagnostic.location)
  return location_;
}
inline ::Lya::protos::PBLocation* PBDiagnostic::release_location() {
  // @@protoc_insertion_point(field_release:Lya.protos.PBDiagnostic.location)
  
  ::Lya::protos::PBLocation* temp = location_;
  location_ = NULL;
  return temp;
}
inline void PBDiagnostic::set_allocated_location(::Lya::protos::PBLocation* location) {
  delete location_;
  location_ = location;
  if (location) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Lya.protos.PBDiagnostic.location)
}

// -------------------------------------------------------------------

// PBLocation

// uint64 line = 1;
inline void PBLocation::clear_line() {
  line_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PBLocation::line() const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBLocation.line)
  return line_;
}
inline void PBLocation::set_line(::google::protobuf::uint64 value) {
  
  line_ = value;
  // @@protoc_insertion_point(field_set:Lya.protos.PBLocation.line)
}

// uint64 column = 2;
inline void PBLocation::clear_column() {
  column_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PBLocation::column() const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBLocation.column)
  return column_;
}
inline void PBLocation::set_column(::google::protobuf::uint64 value) {
  
  column_ = value;
  // @@protoc_insertion_point(field_set:Lya.protos.PBLocation.column)
}

// uint64 length = 3;
inline void PBLocation::clear_length() {
  length_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PBLocation::length() const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBLocation.length)
  return length_;
}
inline void PBLocation::set_length(::google::protobuf::uint64 value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:Lya.protos.PBLocation.length)
}

// uint64 position = 4;
inline void PBLocation::clear_position() {
  position_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PBLocation::position() const {
  // @@protoc_insertion_point(field_get:Lya.protos.PBLocation.position)
  return position_;
}
inline void PBLocation::set_position(::google::protobuf::uint64 value) {
  
  position_ = value;
  // @@protoc_insertion_point(field_set:Lya.protos.PBLocation.position)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace protos
}  // namespace Lya

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_service_2eproto__INCLUDED
